//
//  Sounds.swift
//  TimeDrip
//
//  Created by Kate MacInnis on 5/27/18.
//  Copyright © 2018 Kate MacInnis. All rights reserved.
//

import Foundation

class Sounds {
    static let soundArray = [
        ["name":"Silence", "file":"silence"],
        ["name":"", "file":"blank"],
        ["name":"Alert Sound: Buzzer", "file":"alertsound-buzzer"],
        ["name":"Alert Sound: Horn", "file":"alertsound-horn"],
        ["name":"Alert Sound: Invasion", "file":"alertsound-invasion"],
        ["name":"Alert Sound: Permission To Panic", "file":"alertsound-permission-to-panic"],
        ["name":"Alert Sound: Schoolbell", "file":"alertsound-schoolbell"],
        ["name":"Ancient Announcement", "file":"ancient-announcement"],
        ["name":"Born Sovy", "file":"born-sovy"],
        ["name":"Dark Magic", "file":"dark-magic"],
        ["name":"Dilemma", "file":"dilemma"],
        ["name":"Dolphin Ride", "file":"dolphin-ride"],
        ["name":"Drifting Through Space", "file":"drifting-through-space"],
        ["name":"Endless Corridor", "file":"endless-corridor"],
        ["name":"Fairy Glen", "file":"fairy-glen"],
        ["name":"Game Groove", "file":"game-groove"],
        ["name":"Jaraxe Guitar", "file":"jaraxe-guitar"],
        ["name":"Lemon Symphony", "file":"lemon-symphony"],
        ["name":"Mellow Citrus", "file":"mellow-citrus"],
        ["name":"Mouth Music", "file":"mouth-music"],
        ["name":"Music Box", "file":"music-box"],
        ["name":"Orange Modern", "file":"orange-modern"],
        ["name":"Persistant Trooper", "file":"persistant-trooper"],
        ["name":"Rocky Comet", "file":"rocky-comet"],
        ["name":"Rumma Beat", "file":"rumma-beat"],
        ["name":"Stinky Grove", "file":"stinky-grove"],
        ["name":"Theremin Quartet", "file":"theremin-quartet"],
        ["name":"Trapped In A Dream", "file":"trapped-in-a-dream"],
        ["name":"Upbeat Hero", "file":"upbeat-hero"],
    ]

    static let detailedSoundArray = [
         ["name": "Alert Sound: Buzzer",
          "file": "alertsound-buzzer",
          "filename-wav": "alertsound-buzzer.wav",
          "link": "https://freesound.org/people/kwahmah_02/sounds/244932/",
          "comment": ""],
         ["name": "Alert Sound: Horn",
          "file": "alertsound-horn",
          "filename-wav": "alertsound-horn.wav",
          "link": "https://freesound.org/people/guitarguy1985/sounds/68999/",
          "comment": ""],
         ["name": "Alert Sound: Invasion",
          "file": "alertsound-invasion",
          "filename-wav": "alertsound-invasion.wav",
          "link": "https://freesound.org/people/o_ultimo/sounds/324394/",
          "comment": ""],
         ["name": "Alert Sound: Permission To Panic",
          "file": "alertsound-permission-to-panic",
          "filename-wav": "alertsound-permission-to-panic.wav",
          "link": "https://freesound.org/people/jamesabdulrahman/sounds/263621/",
          "comment": ""],
         ["name": "Alert Sound: Schoolbell",
          "file": "alertsound-schoolbell",
          "filename-wav": "alertsound-schoolbell.wav",
          "link": "https://freesound.org/people/vtkproductions.com/sounds/64073/",
          "comment": ""],
         ["name": "Ancient Announcement",
          "file": "ancient-announcement",
          "filename-wav": "ancient-announcement.wav",
          "link": "https://freesound.org/people/FK_Prod/sounds/190028/",
          "comment": ""],
         ["name": "Born Sovy",
          "file": "born-sovy",
          "filename-wav": "born-sovy.wav",
          "link": "https://freesound.org/people/sovy/sounds/166112/",
          "comment": ""],
         ["name": "Dark Magic",
          "file": "dark-magic",
          "filename-wav": "dark-magic.wav",
          "link": "https://freesound.org/people/rhodesmas/sounds/321718/",
          "comment": ""],
         ["name": "Dilemma",
          "file": "dilemma",
          "filename-wav": "dilemma.wav",
          "link": "https://freesound.org/people/RokZRooM/sounds/344778/",
          "comment": ""],
         ["name": "Dolphin Ride",
          "file": "dolphin-ride",
          "filename-wav": "dolphin-ride.wav",
          "link": "https://freesound.org/people/kimp10/sounds/341580/",
          "comment": ""],
         ["name": "Drifting Through Space",
          "file": "drifting-through-space",
          "filename-wav": "drifting-through-space.wav",
          "link": "https://freesound.org/people/LittleRobotSoundFactory/sounds/323840/",
          "comment": ""],
         ["name": "Endless Corridor",
          "file": "endless-corridor",
          "filename-wav": "endless-corridor.wav",
          "link": "https://freesound.org/people/LittleRobotSoundFactory/sounds/323833/",
          "comment": ""],
         ["name": "Fairy Glen",
          "file": "fairy-glen",
          "filename-wav": "fairy-glen.wav",
          "link": "https://freesound.org/people/Thoribass/sounds/254822/",
          "comment": ""],
         ["name": "Game Groove",
          "file": "game-groove",
          "filename-wav": "game-groove.wav",
          "link": "https://freesound.org/people/yummie/sounds/410574/",
          "comment": ""],
         ["name": "Jaraxe Guitar",
          "file": "jaraxe-guitar",
          "filename-wav": "jaraxe-guitar.wav",
          "link": "https://freesound.org/people/JarAxe/sounds/85203/",
          "comment": ""],
         ["name": "Lemon Symphony",
          "file": "lemon-symphony",
          "filename-wav": "lemon-symphony.wav",
          "link": "https://freesound.org/people/Lemoncreme/sounds/185347/",
          "comment": ""],
         ["name": "Mellow Citrus",
          "file": "mellow-citrus",
          "filename-wav": "mellow-citrus.wav",
          "link": "https://freesound.org/people/Lemoncreme/sounds/203099/",
          "comment": ""],
         ["name": "Mouth Music",
          "file": "mouth-music",
          "filename-wav": "mouth-music.wav",
          "link": "https://freesound.org/people/nigelnix/sounds/160891/",
          "comment": ""],
         ["name": "Music Box",
          "file": "music-box",
          "filename-wav": "music-box.wav",
          "link": "https://freesound.org/people/KAMARIN/sounds/417934/",
          "comment": ""],
         ["name": "Orange Modern",
          "file": "orange-modern",
          "filename-wav": "orange-modern.wav",
          "link": "https://freesound.org/people/orangefreesounds/sounds/326479/",
          "comment": ""],
         ["name": "Persistant Trooper",
          "file": "persistant-trooper",
          "filename-wav": "persistant-trooper.wav",
          "link": "https://freesound.org/people/yummie/sounds/410575/",
          "comment": ""],
         ["name": "Rocky Comet",
          "file": "rocky-comet",
          "filename-wav": "rocky-comet.wav",
          "link": "https://freesound.org/people/Pixelcomet/sounds/106880/",
          "comment": ""],
         ["name": "Rumma Beat",
          "file": "rumma-beat",
          "filename-wav": "rumma-beat.wav",
          "link": "https://freesound.org/people/guru12192/sounds/337802/",
          "comment": ""],
         ["name": "Stinky Grove",
          "file": "stinky-grove",
          "filename-wav": "stinky-grove.wav",
          "link": "https://freesound.org/people/rap2h/sounds/151541/",
          "comment": ""],
         ["name": "Theremin Quartet",
          "file": "theremin-quartet",
          "filename-wav": "theremin-quartet.wav",
          "link": "https://freesound.org/people/moatdd/sounds/268603/",
          "comment": ""],
         ["name": "Trapped In A Dream",
          "file": "trapped-in-a-dream",
          "filename-wav": "trapped-in-a-dream.wav",
          "link": "https://freesound.org/people/LittleRobotSoundFactory/sounds/323844/",
          "comment": ""],
         ["name": "Upbeat Hero",
          "file": "upbeat-hero",
          "filename-wav": "upbeat-hero.wav",
          "link": "https://freesound.org/people/yummie/sounds/410578/",
          "comment": ""]
    ]

    static func getIndex(filename: String) -> Int? {
        for i in 0...soundArray.count - 1 {
            if soundArray[i]["file"] == filename {
                return i
            }
        }
        return nil
    }

    static func getIndex(name: String) -> Int? {
        for i in 0...soundArray.count {
            if soundArray[i]["name"] == name {
                return i
            }
        }
        return nil
    }

}
